# Generated by Django 2.2.1 on 2019-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32, verbose_name='科目名')),
            ],
            options={
                'db_table': 'course',
                'verbose_name': '科目',
            },
        ),
    ]
