# Generated by Django 2.2.1 on 2019-12-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='click',
            new_name='art_click',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='recommend',
            new_name='art_recommend',
        ),
    ]
