# Generated by Django 2.2.1 on 2019-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '科目', 'verbose_name_plural': '科目'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='images/b01.jpg', upload_to='images', verbose_name='科目图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=32, verbose_name='科目名称'),
        ),
    ]
