# Generated by Django 2.2.1 on 2020-01-03 21:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20191201_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32, verbose_name='旅游地点')),
                ('city_img', models.ImageField(upload_to='images', verbose_name='标志图片')),
                ('city_description', ckeditor.fields.RichTextField(verbose_name='城市描述')),
            ],
            options={
                'db_table': 'city',
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_img', models.ImageField(upload_to='images', verbose_name='景点图片')),
                ('art_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.City', verbose_name='城市外键')),
            ],
            options={
                'db_table': 'images',
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
            },
        ),
    ]
