# Generated by Django 2.2.1 on 2020-01-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_city_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='art_type',
            new_name='images_type',
        ),
    ]
