# Generated by Django 2.2.1 on 2020-01-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20200103_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='留言内容')),
                ('date', models.DateField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '留言',
                'db_table': 'comment',
                'verbose_name': '留言',
            },
        ),
    ]
